version: "3.8"

volumes:
  jenkins-data: {}          # Persistent Jenkins home
  docker-certs-ca: {}       # CA certs for DinD
  docker-certs-client: {}   # Client certs for Jenkins
  dind-data: {}             # Docker daemon image/layer cache

networks:
  jenkins: {}

services:
  dind:
    image: docker:27-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    networks:
      jenkins:
        aliases:
          - docker
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - dind-data:/var/lib/docker
    healthcheck:
      test: ["CMD-SHELL", "docker info >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 8

  jenkins:
    build:
      context: ./jenkins
    user: root
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc.yaml
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_LOG_LEVEL: "FINE"
      CASC_DEBUG: "true"
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home      # Jenkins home (workspace, config, plugins)
      - docker-certs-client:/certs/client:ro # Certs for TLS Docker access
      - /var/run/docker.sock:/var/run/docker.sock # Docker socket for host access
    depends_on:
      dind:
        condition: service_healthy
    restart: unless-stopped
