version: '3.9'

services:
  jenkins:
    image: docker/jenkins-docker:2.416.2-lts
    container_name: jenkins
    user: root
    environment:
      # Use host Docker
      DOCKER_HOST: "unix:///var/run/docker.sock"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"    # Jenkins Web UI
      - "50000:50000"  # Jenkins agent port
    restart: unless-stopped

volumes:
  jenkins-data:
